[meta]
name = "Participation Medals"
author = "AdamJC20"
category = "Race"
version = "1.9.0"
siteid = 590

[script]
dependencies = [ "NadeoServices" ]
optional_dependencies = [ "MLHook", "UltimateMedalsExtended" ]
module = "ParticipationMedals"
exports = [ "src/Export.as" ]
shared_exports = [ "src/ExportShared.as" ]
