[meta]
name = "Warrior Medals"
author = "Ezio"
category = "Race"
version = "1.5.1"
siteid = 590

[script]
dependencies = [ "NadeoServices" ]
module = "WarriorMedals"
exports = [ "src/Export.as" ]
shared_exports = [ "src/ExportShared.as" ]
