[meta]
name = "Warrior Medals"
author = "Ezio"
category = "Race"
version = "1.2.1"
siteid = 590

[script]
module = "WarriorMedals"
exports = [ "src/Export.as" ]
shared_exports = [ "src/ExportShared.as" ]
